#line 1 "markdown-new.lex.c"

#line 3 "markdown-new.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 62
#define YY_END_OF_BUFFER 63
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[564] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   63,   61,   55,    3,   61,   61,
       54,   47,   61,   61,   61,   61,   52,   61,   61,   50,
       43,   44,   61,   15,    1,   61,   55,    4,   47,   61,
       61,   61,   61,    7,   62,   31,   31,   32,   31,   31,
       35,   35,   36,   35,   35,   39,   39,   40,   39,   39,
        3,   51,   46,    0,    0,    0,    0,    0,    0,    0,

       41,   53,   49,    0,   56,   14,    1,    0,    0,    0,
       10,    1,    0,    0,    4,    5,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    2,
        0,   25,    0,    0,   31,   32,    0,   35,   36,    0,
       39,   40,    0,   45,    0,    0,    0,    0,    0,    0,
        0,    0,   48,   42,   13,    0,    0,    0,    8,    0,
        4,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   24,    0,   16,    0,   18,
        0,    0,    0,    0,    0,    0,   60,    0,    0,    0,
        0,    0,   26,   12,    0,    0,    9,    0,   15,    4,
        0,    0,    0,    0,    0,    0,    0,   28,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   23,    0,
        0,   21,    0,   16,   17,    6,    0,    0,    0,   58,
        0,    0,   57,    0,    0,    0,   11,    0,    0,    0,
        4,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   37,    0,    0,    0,    0,    0,    0,    0,    0,
       22,    0,    0,    0,   19,    0,   16,    6,    6,    0,
        0,    0,   59,    0,    0,    0,    0,    4,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   20,    0,   16,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   33,    0,    0,    0,   16,    0,    0,    0,   38,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   29,    0,   16,    0,    0,
       27,    0,    0,    0,    0,   34,    0,    0,    0,    0,
       30,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    1,    1,    1,    9,
       10,   11,   12,    1,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   16,   16,   16,   18,    1,   19,
        1,   20,    1,   21,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       22,   23,   24,    1,   25,   26,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,    1,   16,   52,   16,   53,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[54] =
    {   0,
        1,    2,    3,    3,    2,    4,    1,    4,    4,    4,
        4,    4,    4,    4,    1,    2,    2,    1,    2,    3,
        2,    2,    4,    5,    4,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1
    } ;

static const flex_int16_t yy_base[580] =
    {   0,
        0,   52,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  105,    0,  158,    0,
      211,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0, 1063, 1064, 1064, 1064, 1059, 1039,
     1064, 1049, 1046, 1045,    0, 1035, 1064,    0, 1047, 1030,
     1028, 1064, 1000,  263, 1064, 1049,   12, 1043,   22, 1045,
        7,  301,    4,   17, 1064,    0, 1064, 1064, 1046, 1033,
        0, 1064, 1064, 1044, 1031,    0, 1064, 1064, 1042, 1029,
     1064, 1064, 1032, 1029, 1028,    1,  994, 1012, 1007,    0,

     1064, 1064, 1012, 1010, 1064,   38, 1064, 1032,   64, 1029,
     1064, 1064,   77,   81, 1025, 1064,  254,  349,  394,   60,
      265,  993,   53,  260,  439,    0,   65,   62,   18,  242,
      482,  305,  271,  524,  546,  367,    2, 1003,  991, 1064,
     1026,  591, 1015, 1014,    0, 1064,  981,    0, 1064,  980,
        0, 1064,  979, 1064,  269, 1010,  984,  979,  974,  984,
      986,  993, 1064, 1064,  355,  363, 1011,  381, 1064,  408,
     1007,  237,  344,   71,  277,  360,  270,  994,  323,  985,
      968,  981,  968,   15,  974,  978,  962,  238,  973,  964,
      974,  957,  265,  962,  955,  365,  954,  276,  959,  375,

      445,  384,  386,  971,  970,  255,  952,  962,  292,  959,
      963,  941,  963,  957,  496,  420,  385,  941,   58,  952,
      941,  940,  941,    7,  956,  944,  938,  378,  954,  933,
      952,  311,  419,  945,  949,  935,  925,  933,  503,  334,
      510,  929,  942,  927,  928,  470,  463,  961,  963, 1064,
      954,  937,  919,  916,  438,  911, 1064,  480,  931,  943,
      918,  921, 1064,  538,  543,  554, 1064,  580,    0,  950,
      387,  918,  392,  912,  361,  413,  436, 1064,  466,  911,
      913,  909,  914,  924,  915,  919,  913,  916,  917,  894,
      898,  895,  896,  895,  909,  908,  602,  899,  910,  909,

      897,  903,  895,  416,  886,  885,  891,  890,  898,  889,
      899,  878,  884,  890,  891,  890,  883,  882,  871,  426,
      873,  887,  884,  441,  872,  886,  879,  860,  868,  874,
      862,  876,  868,  861,  864,  453,  865,  863,  881,  862,
      869,  852,  856,  869,  864,  856,  864,  861,  608,  886,
      885, 1064,  516,  881, 1064,  478,  844,  836,  853, 1064,
      536,  833, 1064,  869,  459,  837,  621,  625,  629,  634,
      874,  841,  849,  848,  849,  846,  835,  637,  838,  833,
      846,  837,  840,  826,  842,  830,  832,  825,  835,  834,
      836,  818,  830,  829,  643,  820,  812,  827,  825,  817,

      814,  657,  809,  825,  807,  821,  805,  807,  800,  807,
      801,  802,  808,  813,  803,  811,  802,  798,  806,  809,
      815, 1064,  803,  782,  805,  785,  800,  798,  791,  786,
     1064,  821,  820,  819, 1064,  557,  815,  520, 1064,  787,
      783,  800, 1064,  804,  777,  651,  663, 1064,  766,  771,
      769,  776,  772,  769,  771,  765,  768,  764,  766,  766,
      770,  766,  770,  757,  759,  769,  755,  675,  754,  766,
      765,  755,  764,  747,  753,  756,  744,  748,  748,  741,
      755,  739,  743,  737,  751,  750,  747,  742,  675,  674,
      712, 1064,  711,  707,  672,  682,  564,    0,  681,  673,

      666,  679,  669,  661,  667,  659,  675,  659,  658,  671,
      655,  669,  649,  667,  666,  654,  647,  648,  671,  649,
      661, 1064,  622,  628,  646,  641,  599,  598,  583, 1064,
      594,  596,  562,  550,  547,  533,  529,  534,  518,  513,
      505,  489,  482,  467,  485, 1064,  468, 1064,  472,  597,
     1064,  434,  396,  608,  611, 1064,  667,  369,  352,  672,
     1064,  684, 1064,  720,  725,  359,  282,  270,    0,  730,
      734,  739,  744,  749,  754,  759,  764,  769,  774
    } ;

static const flex_int16_t yy_def[580] =
    {   0,
      564,  564,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  563,   17,  563,   19,
      563,   21,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  566,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  567,  563,  563,  563,  563,
      568,  563,  563,  563,  563,  569,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  570,

      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,   72,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  567,  563,  563,  568,  563,  563,
      569,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  570,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  134,  571,  563,  572,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,

      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,   64,  563,
      563,  563,  563,  563,  571,  571,  572,  563,  572,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,

      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  573,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,

      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      573,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  574,  563,  563,
      563,  563,  563,  563,  563,  563,  575,  576,  563,  563,

      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  577,  563,
      574,  563,  563,  563,  563,  563,  563,  563,  575,  563,
      575,  576,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  577,  563,  563,  563,  563,  578,
      563,  563,  563,  579,  578,  563,  578,  563,  563,  579,
      563,  579,    0,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563
    } ;

static const flex_int16_t yy_nxt[1118] =
    {   0,
      151,   47,   48,   49,   47,   50,  140,  141,  142,   51,
       52,  116,   53,  113,  107,  108,  114,   54,   55,   94,
       56,   57,   58,   59,   60,   61,  116,  211,  242,  143,
      212,   96,   93,   97,  144,  157,  243,  132,   98,  165,
      107,  108,  166,   99,  218,  284,  158,  327,  167,  167,
      167,   62,   63,   64,   65,   66,   67,   50,  219,   68,
      285,   51,   69,   70,   71,  113,  107,  108,  168,   54,
       72,   73,   56,   57,   58,   59,   60,   61,  113,  107,
      108,  113,  113,  107,  108,  170,  193,  202,  216,  321,
      194,  213,  217,  203,  195,  214,  204,  273,  158,  215,

      196,  217,  322,   74,   63,   76,   77,   78,   79,   77,
       77,   76,   77,   77,   77,   77,   77,   77,   77,   76,
       77,   77,   76,   80,   77,   77,   77,   77,   77,   77,
       77,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   77,   76,   81,   82,
       83,   84,   82,   82,   81,   82,   82,   82,   82,   82,
       82,   82,   81,   82,   82,   81,   85,   82,   82,   82,
       82,   82,   82,   82,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,

       81,   81,   81,   81,   81,   81,   81,   81,   81,   82,
       81,   86,   87,   88,   89,   87,   87,   86,   87,   87,
       87,   87,   87,   87,   87,   86,   87,   87,   86,   90,
       87,   87,   87,   87,   87,   87,   87,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   87,   86,  106,  107,  108,  109,  563,  220,
      148,  271,  132,  110,  110,  110,  132,  203,  132,  132,
      204,  255,  145,  221,  276,  172,  256,  173,  222,  179,
      205,  197,  174,  310,  132,  198,  199,  175,  176,  200,

      261,  161,  132,  132,  292,  206,  293,  177,  177,  177,
      132,  177,  132,  132,  111,  117,  132,  225,  132,  178,
      257,  300,  132,  225,  179,  278,  279,  118,  119,  120,
      121,  122,  123,  312,  124,  125,  132,  126,  127,  128,
      129,  130,  131,  132,  133,  134,  135,  136,  137,  138,
      139,  177,  177,  177,  336,  177,  264,  107,  108,  265,
      132,  337,  101,  178,  113,  107,  108,  266,  179,  177,
      177,  177,  345,  177,  205,  276,  180,  181,  182,  346,
      179,  178,  113,  107,  108,  268,  179,  132,  563,  272,
      183,  132,  184,  185,  296,  186,  177,  177,  177,  132,

      177,  301,  297,  298,  132,  274,  331,  563,  178,  113,
      107,  108,  269,  179,  303,  332,  304,  303,  132,  304,
      187,  259,  132,  188,  319,  305,  306,  276,  189,  307,
      320,  190,  179,  132,  191,  318,  559,  132,  278,  279,
      192,  177,  177,  177,  391,  177,  132,  177,  177,  177,
      255,  177,  132,  178,  262,  256,  403,  338,  179,  178,
      132,  132,  392,  318,  179,  140,  141,  353,  278,  279,
      207,  349,  302,  407,  350,  408,  364,  208,  209,  558,
      351,  351,  351,  210,  177,  177,  177,  417,  177,  257,
      438,  554,  361,  418,  132,  439,  178,  362,  177,  177,

      177,  179,  177,  260,  546,  177,  177,  177,  223,  177,
      178,  132,  177,  177,  177,  179,  177,  178,  140,  141,
      436,  352,  179,  132,  178,  224,  177,  177,  177,  179,
      177,  363,  438,  344,  132,  317,  347,  439,  178,  367,
      107,  108,  368,  179,  113,  107,  108,  369,  361,  132,
      226,  132,  227,  362,  228,  113,  107,  108,  370,  140,
      141,  246,  229,  132,  230,  231,  530,  531,  553,  232,
      233,  234,  235,  236,  132,  132,  237,  238,  132,  239,
      240,  113,  107,  108,  106,  530,  531,  363,  132,  241,
      552,  132,  246,  140,  141,  247,  530,  531,  248,  556,

      557,  249,  249,  249,  177,  177,  177,  132,  177,  431,
      561,  562,  432,  556,  557,  551,  178,  550,  433,  433,
      433,  179,  113,  107,  108,  113,  113,  107,  108,  446,
      113,  107,  108,  447,  384,  113,  107,  108,  165,  177,
      177,  177,  250,  177,  549,  177,  177,  177,  548,  177,
      431,  178,  113,  107,  108,  499,  179,  178,  547,  177,
      177,  177,  179,  177,  113,  107,  108,  264,  453,  556,
      557,  178,  132,  469,  561,  562,  179,  177,  177,  177,
      522,  177,  113,  107,  108,  367,  561,  562,  132,  178,
      546,  474,  544,  543,  179,  542,  541,  540,  132,  539,

      538,  537,  132,  536,  132,  535,  132,  534,  533,  132,
      132,  132,  528,  527,  526,  349,  525,  524,  523,  512,
       46,   46,   46,   46,   46,   75,   75,   75,   75,   75,
      162,  162,  162,  162,  275,  275,  275,  275,  275,  277,
      277,  277,  277,  277,  421,  421,  421,  421,  421,  521,
      521,  521,  521,  521,  529,  529,  529,  529,  529,  532,
      532,  522,  532,  532,  545,  545,  545,  545,  545,  555,
      555,  555,  555,  555,  560,  560,  560,  560,  560,  132,
      132,  132,  132,  520,  519,  518,  132,  132,  517,  132,
      516,  515,  514,  132,  132,  513,  132,  132,  132,  132,

      511,  510,  132,  509,  508,  507,  506,  132,  505,  132,
      132,  504,  503,  502,  132,  501,  500,  260,  498,  497,
      496,  495,  494,  493,  492,  491,  132,  132,  132,  132,
      132,  490,  132,  132,  422,  489,  488,  487,  486,  485,
      132,  484,  483,  482,  481,  132,  480,  479,  478,  477,
      476,  475,  132,  473,  132,  472,  471,  132,  470,  468,
      467,  466,  465,  464,  132,  463,  462,  461,  460,  459,
      458,  457,  456,  455,  454,  132,  132,  452,  451,  450,
      449,  448,  445,  444,  443,  442,  441,  440,  437,  435,
      434,  430,  429,  428,  132,  427,  426,  425,  424,  423,

      422,  420,  419,  132,  416,  415,  414,  413,  412,  132,
      132,  411,  410,  409,  406,  405,  404,  402,  132,  132,
      401,  400,  399,  398,  397,  396,  132,  395,  394,  132,
      393,  132,  390,  389,  388,  387,  386,  385,  132,  132,
      383,  382,  381,  380,  132,  379,  378,  377,  376,  375,
      132,  374,  373,  372,  132,  336,  310,  371,  366,  365,
      364,  260,  360,  359,  358,  357,  356,  355,  354,  132,
      132,  348,  132,  343,  342,  341,  340,  339,  335,  334,
      333,  330,  329,  328,  326,  325,  324,  323,  132,  316,
      315,  314,  132,  313,  132,  311,  309,  308,  132,  299,

      295,  294,  291,  290,  289,  132,  288,  287,  286,  283,
      282,  281,  280,  179,  270,  267,  263,  260,  262,  261,
      260,  259,  258,  254,  253,  252,  143,  251,  140,  245,
      244,  201,  171,  169,  107,  164,  163,  161,  160,  159,
      156,  155,  154,  153,  152,  150,  149,  147,  146,  116,
      115,  112,  105,  104,  103,  102,  100,   95,   94,   93,
       92,   91,  563,   45,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,

      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563
    } ;

static const flex_int16_t yy_chk[1118] =
    {   0,
      569,    1,    1,    1,    1,    1,   73,   73,   73,    1,
        1,   71,    1,   67,   67,   67,   67,    1,    1,   71,
        1,    1,    1,    1,    1,    1,   69,  126,  137,   74,
      126,   55,   69,   55,   74,   96,  137,  224,   55,  106,
      106,  106,  106,   55,  129,  184,   96,  224,  106,  106,
      106,    1,    1,    2,    2,    2,    2,    2,  129,    2,
      184,    2,    2,    2,    2,  109,  109,  109,  109,    2,
        2,    2,    2,    2,    2,    2,    2,    2,  113,  113,
      113,  113,  114,  114,  114,  114,  120,  123,  128,  219,
      120,  127,  128,  123,  120,  127,  123,  174,  123,  127,

      120,  174,  219,    2,    2,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   64,   64,   64,   64,  117,  130,
      568,  172,  188,   64,   64,   64,  124,  172,  188,  130,
      172,  155,  567,  130,  177,  117,  155,  117,  130,  177,
      124,  121,  117,  206,  121,  121,  121,  117,  117,  121,

      206,  133,  121,  124,  193,  124,  193,  132,  132,  132,
      121,  132,  133,  198,   64,   72,  133,  133,  175,  132,
      155,  198,  175,  175,  132,  179,  179,   72,   72,   72,
       72,   72,   72,  209,   72,   72,  209,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,  118,  118,  118,  232,  118,  165,  165,  165,  165,
      173,  232,  566,  118,  166,  166,  166,  166,  118,  136,
      136,  136,  240,  136,  173,  275,  118,  118,  118,  240,
      275,  136,  168,  168,  168,  168,  136,  173,  176,  173,
      118,  559,  118,  118,  196,  118,  119,  119,  119,  558,

      119,  200,  196,  196,  136,  176,  228,  176,  119,  170,
      170,  170,  170,  119,  202,  228,  202,  271,  200,  271,
      119,  202,  200,  119,  217,  203,  203,  276,  119,  203,
      217,  119,  276,  273,  119,  273,  553,  119,  277,  277,
      119,  125,  125,  125,  304,  125,  233,  201,  201,  201,
      255,  201,  320,  125,  216,  255,  320,  233,  125,  201,
      233,  216,  304,  216,  201,  247,  247,  247,  279,  279,
      125,  246,  201,  324,  246,  324,  365,  125,  125,  552,
      246,  246,  246,  125,  131,  131,  131,  336,  131,  255,
      356,  549,  258,  336,  547,  356,  131,  258,  215,  215,

      215,  131,  215,  365,  545,  239,  239,  239,  131,  239,
      215,  544,  241,  241,  241,  215,  241,  239,  353,  353,
      353,  246,  239,  543,  241,  131,  134,  134,  134,  241,
      134,  258,  438,  239,  542,  215,  241,  438,  134,  264,
      264,  264,  264,  134,  265,  265,  265,  265,  361,  541,
      134,  540,  134,  361,  134,  266,  266,  266,  266,  436,
      436,  436,  134,  539,  134,  134,  497,  497,  538,  134,
      134,  134,  135,  135,  537,  135,  135,  135,  536,  135,
      135,  268,  268,  268,  268,  529,  529,  361,  535,  135,
      534,  135,  142,  142,  142,  142,  531,  531,  142,  550,

      550,  142,  142,  142,  297,  297,  297,  533,  297,  349,
      554,  554,  349,  555,  555,  532,  297,  528,  349,  349,
      349,  297,  367,  367,  367,  367,  368,  368,  368,  368,
      369,  369,  369,  369,  297,  370,  370,  370,  370,  378,
      378,  378,  142,  378,  527,  395,  395,  395,  526,  395,
      525,  378,  446,  446,  446,  446,  378,  395,  524,  402,
      402,  402,  395,  402,  447,  447,  447,  447,  378,  557,
      557,  402,  523,  395,  560,  560,  402,  468,  468,  468,
      521,  468,  499,  499,  499,  499,  562,  562,  520,  468,
      519,  402,  518,  517,  468,  516,  515,  514,  513,  512,

      511,  510,  509,  508,  507,  506,  505,  504,  503,  502,
      501,  500,  496,  495,  494,  493,  491,  490,  489,  468,
      564,  564,  564,  564,  564,  565,  565,  565,  565,  565,
      570,  570,  570,  570,  571,  571,  571,  571,  571,  572,
      572,  572,  572,  572,  573,  573,  573,  573,  573,  574,
      574,  574,  574,  574,  575,  575,  575,  575,  575,  576,
      576,  488,  576,  576,  577,  577,  577,  577,  577,  578,
      578,  578,  578,  578,  579,  579,  579,  579,  579,  487,
      486,  485,  484,  483,  482,  481,  480,  479,  478,  477,
      476,  475,  474,  473,  472,  471,  470,  469,  467,  466,

      465,  464,  463,  462,  461,  460,  459,  458,  457,  456,
      455,  454,  453,  452,  451,  450,  449,  445,  444,  442,
      441,  440,  437,  434,  433,  432,  430,  429,  428,  427,
      426,  425,  424,  423,  421,  420,  419,  418,  417,  416,
      415,  414,  413,  412,  411,  410,  409,  408,  407,  406,
      405,  404,  403,  401,  400,  399,  398,  397,  396,  394,
      393,  392,  391,  390,  389,  388,  387,  386,  385,  384,
      383,  382,  381,  380,  379,  377,  376,  375,  374,  373,
      372,  371,  366,  364,  362,  359,  358,  357,  354,  351,
      350,  348,  347,  346,  345,  344,  343,  342,  341,  340,

      339,  338,  337,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  323,  322,  321,  319,  318,  317,
      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  303,  302,  301,  300,  299,  298,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  274,  272,  270,  262,  261,
      260,  259,  256,  254,  253,  252,  251,  249,  248,  245,
      244,  243,  242,  238,  237,  236,  235,  234,  231,  230,
      229,  227,  226,  225,  223,  222,  221,  220,  218,  214,
      213,  212,  211,  210,  208,  207,  205,  204,  199,  197,

      195,  194,  192,  191,  190,  189,  187,  186,  185,  183,
      182,  181,  180,  178,  171,  167,  162,  161,  160,  159,
      158,  157,  156,  153,  150,  147,  144,  143,  141,  139,
      138,  122,  115,  110,  108,  104,  103,   99,   98,   97,
       95,   94,   93,   90,   89,   85,   84,   80,   79,   70,
       68,   66,   63,   61,   60,   59,   56,   54,   53,   52,
       50,   49,   45,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,

      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "markdown-new.lex"
#line 2 "markdown-new.lex"

#include <string.h>
#include "strutils.h"
#include "logutils.h"
#include "lex-state-stack.h"
#include "node.h"
#include "markdown-new.y.h"

#undef _ONLYLEX
#undef _ISDEBUGLEX

/*
#define _ONLYLEX
*/


#ifdef _ONLYLEX
#define _ISDEBUGLEX
#endif

#ifdef _ONLYLEX
#define RETURN(token)
#define SETYYLVAL(str)
#else
#define RETURN(token) return token
#define SETYYLVAL(str) yylval.text = strdup(str)
#endif

#ifdef _ISDEBUGLEX
#define P(token) fprintf(stderr, "%s|%s|%s", token, \
    strcmp("LINEBREAK",token)==0||strcmp("BLANKLINE",token)==0?"":yytext, \
    strcmp("LINEBREAK",token)==0||strcmp("BLANKLINE",token)==0?"\n":""); BeginToken(yytext);
#else
#define P(token) BeginToken(yytext);
#endif

#ifndef _ONLYLEX
/* YY_INPUT macro: connect GetNextChar with yacc */
#define YY_INPUT(buf,result,max_size)  { \
    result = GetNextChar(buf, max_size); \
    if (  result <= 0  ) \
      result = YY_NULL; \
}
#endif



/* prototypes */
extern int yylineno;
extern int state;


#ifdef _ONLYLEX
void BeginToken(char *t) {}
#else
/* from input.c */
extern int GetNextChar(char *b, int maxBuffer);
extern void BeginToken(char *t);
#endif

/* local functions */
static void enterState(int state, char *desc) {
    lex_state_push_stack(state, desc);
    BEGIN state;
}
static void restoreState() {
    lex_state_pop_stack();
    t_lex_state_item *item = lex_state_top_stack();
    if (item) {
        BEGIN item -> state;
    }
    else {
        /**
         * 1. `BEGIN 0` is the same as `BEGIN INITIAL`
         * 2. but the macro INITIAL is defined later, it can not be used here
         */
        BEGIN 0;
    }
}
static void popWhenTopStateIs(int state) {
    t_lex_state_item *item = lex_state_top_stack();
    if (item && item->state == state) {
        restoreState();
    }
}
static void clearAllState() {
    while( lex_state_pop_stack() ) {
    }
    restoreState();
}

#line 968 "markdown-new.lex.c"
#line 96 "markdown-new.lex"
    /* lexer states */




    /* blankline ^[ ]{0,4}\r?\n */
#line 976 "markdown-new.lex.c"

#define INITIAL 0
#define ESCAPE 1
#define CODEBLOCK 2
#define XCODEBLOCK 3
#define CODESPAN 4
#define XCODESPAN 5
#define INDENTLIST 6
#define SHTMLBLOCK 7
#define SCRIPTBLOCK 8
#define STYLEBLOCK 9
#define SVGBLOCK 10
#define TABLEROW 11
#define LINKSTART 12
#define LINKATTR 13
#define ATTRSTART 14
#define XEMSTART 15
#define YEMSTART 16
#define XSTRONGSTART 17
#define YSTRONGSTART 18
#define INDENTTABLEROW 19
#define INDENTQUOTE 20
#define QUOTESTART 21

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 115 "markdown-new.lex"


    /* special chars: "\[]^-?.*+|()$/{}%<> */

#line 1222 "markdown-new.lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 564 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1064 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 119 "markdown-new.lex"
{ yylineno++; SETYYLVAL(yytext); P("BLANKLINE"); RETURN(BLANKLINE); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 120 "markdown-new.lex"
{ yylineno++; SETYYLVAL(yytext); P("QUOTEBLANKLINE"); RETURN(QUOTEBLANKLINE); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 121 "markdown-new.lex"
{ yylineno++; SETYYLVAL(yytext); P("LINEBREAK"); RETURN(LINEBREAK); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 123 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_H"); RETURN(LF_H); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 124 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_UL"); RETURN(LF_UL); }
	YY_BREAK
case 6:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 125 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_VERTICAL_HEAD_SEP"); RETURN(LF_VERTICAL_HEAD_SEP); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 126 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_VERTICAL"); RETURN(LF_VERTICAL); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 128 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_INDENT_UL"); RETURN(LF_INDENT_UL); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 129 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_INDENT2_UL"); RETURN(LF_INDENT2_UL); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 131 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_INDENT_VERTICAL"); RETURN(LF_INDENT_VERTICAL); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 133 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_INDENT5"); RETURN(LF_INDENT5); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 134 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_INDENT4"); RETURN(LF_INDENT4); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 135 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_INDENT3"); RETURN(LF_INDENT3); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 136 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_INDENT2"); RETURN(LF_INDENT2); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 137 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_INDENT"); RETURN(LF_INDENT); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 139 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_Q_H"); RETURN(LF_Q_H); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 140 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_Q_UL"); RETURN(LF_Q_UL); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 141 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_Q_VERTICAL"); RETURN(LF_Q_VERTICAL); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 143 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_Q_INDENT_UL"); RETURN(LF_Q_INDENT_UL); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 144 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_Q_INDENT2_UL"); RETURN(LF_Q_INDENT2_UL); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 146 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_Q_INDENT_VERTICAL"); RETURN(LF_Q_INDENT_VERTICAL); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 148 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_Q_INDENT3"); RETURN(LF_Q_INDENT3); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 149 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_Q_INDENT2"); RETURN(LF_Q_INDENT2); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 150 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_Q_INDENT"); RETURN(LF_Q_INDENT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 152 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LF_Q"); RETURN(LF_Q); }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 154 "markdown-new.lex"
{ SETYYLVAL(yytext); P("TEXT"); RETURN(TEXT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 156 "markdown-new.lex"
{ 
                                            SETYYLVAL(yytext); P("SIMPLELINK"); RETURN(SIMPLELINK); }
	YY_BREAK
/* block and functional html tags must be in one line and must start at first column */
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 160 "markdown-new.lex"
{ 
                                            SETYYLVAL(yytext); P("HTMLTAG"); RETURN(HTMLTAG); }
	YY_BREAK
/* script block */
/* problem triggered below: input buffer overflow, can't enlarge buffer because scanner uses REJECT */
/*^\<script[^>]*>/(.|[\r\n])*\<\/script>  { */
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 167 "markdown-new.lex"
{
                                            enterState(SCRIPTBLOCK, "SCRIPTBLOCK"); 
                                            SETYYLVAL(yytext); 
                                            P("SCRIPTSTART"); 
                                            RETURN(SCRIPTSTART); 
                                        }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 173 "markdown-new.lex"
{ 
                                            P("SCRIPTEND"); 
                                            yylineno++;
                                            restoreState(); 
                                            SETYYLVAL("</script>"); 
                                            RETURN(SCRIPTEND);
                                        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 180 "markdown-new.lex"
{ SETYYLVAL(yytext); P("TEXT"); RETURN(TEXT); }
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 181 "markdown-new.lex"
{ 
                                            yylineno++; 
                                            SETYYLVAL(yytext); 
                                            P("TEXT"); 
                                            RETURN(TEXT); 
                                        }
	YY_BREAK
/* style block */
/* ^\<style[^>]*>/(.|[\r\n])*\<\/style>    { */
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 190 "markdown-new.lex"
{
                                            SETYYLVAL(yytext); 
                                            P("STYLESTART"); 
                                            enterState(STYLEBLOCK, "STYLEBLOCK"); 
                                            RETURN(STYLESTART); 
                                        }
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 196 "markdown-new.lex"
{ 
                                            P("STYLEEND"); 
                                            yylineno++;
                                            SETYYLVAL("</style>");
                                            restoreState(); 
                                            RETURN(STYLEEND);
                                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 203 "markdown-new.lex"
{ SETYYLVAL(yytext); P("TEXT"); RETURN(TEXT); }
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 204 "markdown-new.lex"
{ 
                                            yylineno++; 
                                            SETYYLVAL(yytext); 
                                            P("TEXT"); 
                                            RETURN(TEXT); 
                                        }
	YY_BREAK
/* svg block */
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 214 "markdown-new.lex"
{
                                            SETYYLVAL(yytext); 
                                            P("SVGSTART"); 
                                            enterState(SVGBLOCK, "SVGBLOCK"); 
                                            RETURN(SVGSTART); 
                                        }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 220 "markdown-new.lex"
{ 
                                            P("SVGEND"); 
                                            yylineno++;
                                            SETYYLVAL("</svg>"); 
                                            restoreState(); 
                                            RETURN(SVGEND);
                                        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 227 "markdown-new.lex"
{ SETYYLVAL(yytext); P("TEXT"); RETURN(TEXT); }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 228 "markdown-new.lex"
{ 
                                            yylineno++; 
                                            SETYYLVAL(yytext); 
                                            P("TEXT"); 
                                            RETURN(TEXT); 
                                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 234 "markdown-new.lex"
{ SETYYLVAL(yytext); P("ESCAPEDCHAR"); RETURN(ESCAPEDCHAR); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 235 "markdown-new.lex"
{ SETYYLVAL(yytext); P("TRIPLEBACKTICK"); RETURN(TRIPLEBACKTICK); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 236 "markdown-new.lex"
{ SETYYLVAL(yytext); P("BACKTICK"); RETURN(BACKTICK); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 237 "markdown-new.lex"
{ SETYYLVAL(yytext); P("VERTICAL"); RETURN(VERTICAL); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 238 "markdown-new.lex"
{ SETYYLVAL(yytext); P("TRIPLEASTERISK"); RETURN(TRIPLEASTERISK); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 239 "markdown-new.lex"
{ SETYYLVAL(yytext); P("DOUBLEASTERISK"); RETURN(DOUBLEASTERISK); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 240 "markdown-new.lex"
{ SETYYLVAL(yytext); P("ASTERISK"); RETURN(ASTERISK); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 241 "markdown-new.lex"
{ SETYYLVAL(yytext); P("TRIPLEUNDERSCORE"); RETURN(TRIPLEUNDERSCORE); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 242 "markdown-new.lex"
{ SETYYLVAL(yytext); P("DOUBLEUNDERSCORE"); RETURN(DOUBLEUNDERSCORE); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 243 "markdown-new.lex"
{ SETYYLVAL(yytext); P("UNDERSCORE"); RETURN(UNDERSCORE); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 244 "markdown-new.lex"
{ SETYYLVAL(yytext); P("EXCLAMATION_LEFTSQUARE"); RETURN(EXCLAMATION_LEFTSQUARE); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 245 "markdown-new.lex"
{ SETYYLVAL(yytext); P("LEFTSQUARE"); RETURN(LEFTSQUARE); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 246 "markdown-new.lex"
{ SETYYLVAL(yytext); P("RIGHTSQUARE_LEFTBRACKET"); RETURN(RIGHTSQUARE_LEFTBRACKET); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 247 "markdown-new.lex"
{ SETYYLVAL(yytext); P("RIGHTBRACKET"); RETURN(RIGHTBRACKET); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 248 "markdown-new.lex"
{ SETYYLVAL(yytext); P("SPACE"); RETURN(SPACE); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 249 "markdown-new.lex"
{ SETYYLVAL(yytext); P("DOUBLETILDE"); RETURN(DOUBLETILDE); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 250 "markdown-new.lex"
{ SETYYLVAL(yytext); P("SEMI_MINUSSERIES_VERTICAL"); RETURN(SEMI_MINUSSERIES_VERTICAL); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 251 "markdown-new.lex"
{ SETYYLVAL(yytext); P("MINUSSERIES_SEMI_VERTICAL"); RETURN(MINUSSERIES_SEMI_VERTICAL); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 252 "markdown-new.lex"
{ SETYYLVAL(yytext); P("SEMI_MINUSSERIES_SEMI_VERTICAL"); RETURN(SEMI_MINUSSERIES_SEMI_VERTICAL); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 253 "markdown-new.lex"
{ SETYYLVAL(yytext); P("MINUSSERIES_VERTICAL"); RETURN(MINUSSERIES_VERTICAL); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 255 "markdown-new.lex"
{ SETYYLVAL(yytext); P("TEXT"); RETURN(TEXT); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 260 "markdown-new.lex"
ECHO;
	YY_BREAK
#line 1664 "markdown-new.lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ESCAPE):
case YY_STATE_EOF(CODEBLOCK):
case YY_STATE_EOF(XCODEBLOCK):
case YY_STATE_EOF(CODESPAN):
case YY_STATE_EOF(XCODESPAN):
case YY_STATE_EOF(INDENTLIST):
case YY_STATE_EOF(SHTMLBLOCK):
case YY_STATE_EOF(SCRIPTBLOCK):
case YY_STATE_EOF(STYLEBLOCK):
case YY_STATE_EOF(SVGBLOCK):
case YY_STATE_EOF(TABLEROW):
case YY_STATE_EOF(LINKSTART):
case YY_STATE_EOF(LINKATTR):
case YY_STATE_EOF(ATTRSTART):
case YY_STATE_EOF(XEMSTART):
case YY_STATE_EOF(YEMSTART):
case YY_STATE_EOF(XSTRONGSTART):
case YY_STATE_EOF(YSTRONGSTART):
case YY_STATE_EOF(INDENTTABLEROW):
case YY_STATE_EOF(INDENTQUOTE):
case YY_STATE_EOF(QUOTESTART):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 564 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 564 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 563);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 260 "markdown-new.lex"


int yywrap(){
    return 1;
}

#ifdef _ONLYLEX
int main(int argc, char **argv){
    FILE *input = fopen(argv[1], "r");
    yyset_in(input);
    yylex();
    fclose(input);
}
#endif




