#line 2 "markdown.lex.c"

#line 4 "markdown.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 55
#define YY_END_OF_BUFFER 56
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[170] =
    {   0,
       56,   53,   55,   54,   55,   53,   55,   53,   55,   10,
       53,   55,   13,   53,   55,   53,   55,16411,16412,    1,
       54,   55,   53,   55,   53,   55,   34,   53,   55,   53,
       55,   53,   55,   53,   55,    7,   53,   55,   53,   55,
       13,   53,   55,   12,   55,   55,   11,   12,   55,   30,
       55,   31,   55,   30,   55,   20,   55,   21,   55,   20,
       55,   20,   55,   15,   55,   16,   55,   55,   15,   55,
       17,   55,   55,   55,   55,   37,   55,   38,   55,   37,
       55,   42,   55,   43,   55,   55,   42,   55,   46,   55,
       47,   55,   46,   55,   46,   55,   50,   55,   51,   55,

       50,   55,   50,   55,   54,   18,   29,   29,16411,16412,
        1,   29,   29,   29,   29,    1,   54,   34,   23,    2,
        8,   18,   30,   31,   21,   16,   14,   32,   37,   38,
       43,   47,   51, 8219,   34,   25,   36,    3,   35,    8,
        9,   19,   22,   33, 8220,16411,16412,   34,    4,   35,
       24,    9,   34,   49,    5,   35,   26,   34,    6,   35,
       45,   35,   52,   41,   35,   39,   48,   40,   44
    } ;

static yyconst flex_int16_t yy_accept[532] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    4,    6,    8,   10,   13,   16,
       20,   23,   25,   27,   30,   32,   34,   36,   39,   41,
       44,   46,   47,   50,   52,   54,   56,   58,   60,   62,
       64,   66,   68,   69,   71,   73,   74,   75,   76,   78,
       80,   82,   84,   86,   87,   89,   91,   93,   95,   97,
       99,  101,  103,  105,  106,  106,  106,  106,  106,  107,
      108,  111,  112,  113,  114,  115,  116,  118,  118,  118,
      118,  118,  118,  119,  120,  120,  120,  120,  120,  120,

      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      121,  121,  121,  122,  122,  123,  124,  125,  126,  126,
      127,  128,  128,  128,  128,  129,  129,  129,  130,  131,
      132,  132,  133,  133,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  135,  135,  135,  135,  136,  137,  137,
      137,  137,  137,  137,  137,  137,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,

      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  139,  139,  139,  140,  140,  140,  141,
      142,  143,  144,  144,  145,  145,  145,  145,  145,  145,
      145,  145,  146,  148,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,

      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  150,
      150,  150,  151,  152,  152,  152,  153,  153,  153,  153,
      153,  153,  153,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  155,  155,  155,  155,  155,  155,

      155,  155,  155,  156,  156,  156,  157,  158,  158,  158,
      158,  158,  158,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  160,  160,  160,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  162,  162,  162,
      163,  163,  163,  163,  164,  164,  164,  164,  164,  164,

      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  165,  165,  166,  166,  166,  167,  167,  167,  167,
      167,  167,  168,  168,  169,  169,  169,  169,  170,  170,
      170
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    1,    1,    1,    6,
        6,    9,    9,    1,   10,   11,   12,   13,   14,   14,
       14,   14,   14,   14,   15,   15,   15,   16,    1,   17,
        1,   18,    1,   19,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   20,    1,    1,    6,   21,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,    1,    6,    1,    6,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[555] =
    {   0,
        0,   20,   39,   58,    2,    4,    6,   10,   12,   23,
        0,    0,   48,   66,    8,   15,   48,   69,   73,   79,
       81,   84,  873,  874,  874,  869,   65,  874,  850,  103,
      874,  867,  117,  861,  863,  100,  121,   51,   57,  846,
      874,  874,  874,    0,  874,  863,  874,  874,  862,  843,
      874,  874,  860,  841,  874,  120,  856,  125,    0,  874,
      857,  874,  874,  856,  846,  874,  874,  854,  844,  874,
      874,  852,  842,  874,  812,  811,  829,  824,  874,  874,
      165,  874,  846,  179,  843,  162,  874,  187,  844,  841,
      840,  184,  836,  838,  837,  189,  184,  222,  262,  179,

      283,  807,  178,  196,  322,  126,  190,   48,   67,  215,
      360,  278,  202,  397,  419,  238,   80,  817,  805,  874,
      835,  458,    0,  797,  815,    0,  874,  874,  814,  874,
      874,  227,  829,  240,  828,  827,  304,    0,  874,  874,
      791,  874,  790,  874,  789,  791,  786,  796,  798,  819,
      818,  317,  817,  816,  322,  815,  811,  813,  240,  327,
       69,  100,  232,  112,  799,  874,  793,  776,  789,  776,
      145,  782,  786,  770,  142,  781,  772,  782,  765,  150,
      770,  763,  266,  762,  217,  767,  250,   13,  205,  267,
      779,  778,   75,  760,  770,  257,  767,  771,  749,  771,

      765,  253,  284,  303,  749,  280,  760,  749,  748,  749,
      242,  764,  752,  746,  197,  762,  741,  760,  300,  324,
      753,  757,  743,  733,  741,  317,  311,  289,  737,  750,
      735,  736,  874,  769,  366,  763,  765,  362,    0,    0,
      874,  874,  345,  764,  744,  726,  723,  749,  727,  730,
      757,  756,  472,  752,  725,  342,  719,  330,  362,  718,
      720,  716,  721,  731,  722,  726,  720,  723,  724,  701,
      705,  702,  703,  702,  716,  715,   95,  706,  717,  716,
      704,  710,  702,  361,  693,  692,  698,  697,  705,  696,
      706,  685,  691,  697,  698,  697,  690,  689,  678,  329,

      680,  694,  691,  356,  679,  693,  686,  667,  675,  681,
      669,  683,  675,  668,  671,  353,  672,  670,  685,  669,
      676,  659,  663,  676,  671,  663,  671,  668,  874,  690,
      387,  684,  686,  685,  382,    0,  650,  642,  659,  674,
      371,  644,  676,  648,  656,  655,  656,  653,  642,  361,
      645,  640,  653,  644,  647,  633,  649,  637,  639,  632,
      642,  641,  643,  625,  637,  636,  635,  626,  618,  633,
      631,  623,  620,  380,  615,  631,  613,  627,  611,  613,
      606,  613,  607,  608,  614,  619,  609,  617,  608,  604,
      612,  615,  618,  874,  609,  588,  611,  591,  606,  604,

      597,  592,  874,  624,  409,  618,  620,  594,  590,  604,
      609,  584,  874,  573,  578,  576,  583,  579,  576,  578,
      572,  575,  571,  573,  573,  577,  573,  577,  564,  566,
      576,  562,  223,  561,  573,  572,  562,  571,  554,  560,
      563,  551,  555,  555,  548,  562,  546,  550,  544,  558,
      557,  554,  563,  541,  540,  874,  575,  442,  569,  539,
      549,  203,    0,  558,  539,  532,  545,  535,  527,  533,
      525,  541,  525,  524,  537,  521,  535,  515,  533,  532,
      520,  514,  515,  536,  499,  510,  874,  479,  496,  477,
      443,  465,  404,  874,  413,  464,    0,  439,  443,  441,

      430,  429,  439,  418,  421,  403,  396,  395,  390,  404,
      874,  398,  874,  400,  421,  874,  387,  357,  276,  423,
      425,  874,  432,  874,   67,   23,  450,  874,  461,  874,
      487,  490,  493,  496,  499,  502,  505,  508,  511,  514,
      517,  520,  523,  526,  529,  532,  535,  538,  541,    1,
      544,    0,  547,  550
    } ;

static yyconst flex_int16_t yy_def[555] =
    {   0,
      531,  531,  532,  532,  533,  533,  534,  534,  535,  535,
      536,  536,  536,  536,  537,  537,  538,  538,  539,  539,
      540,  540,  530,  530,  530,  530,  530,  530,  530,  541,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  542,  530,  542,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  543,  530,
      543,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      541,  530,  530,  530,  530,  530,  530,  530,  530,   33,
      530,  530,  530,  530,  530,  530,   37,  530,  530,  530,

      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  111,  530,  530,  530,  530,
      530,  530,  544,  530,  530,  542,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  543,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,   84,
      530,  530,  530,  530,  530,   33,  530,  530,  530,  530,
      530,  530,  114,  545,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  116,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,

      530,  116,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  116,  530,  116,  530,  530,
      530,  530,  530,  530,  122,  530,  530,  530,  544,  546,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
       84,  530,  541,  530,  530,  530,  530,  545,  545,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  116,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,

      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  547,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      122,  530,  530,  530,  530,  546,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  116,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  226,  530,  530,  530,
      530,  530,  530,  226,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  547,  530,  530,  530,  530,  530,  530,  530,

      530,  530,  530,  530,  122,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  226,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  548,  530,  530,  530,  530,  530,  530,  530,
      530,  549,  550,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  551,  530,  548,  530,  530,  530,  530,
      530,  530,  549,  530,  549,  550,  552,  530,  530,  530,

      530,  530,  530,  530,  530,  530,  530,  530,  530,  551,
      530,  530,  530,  530,  553,  530,  552,  530,  530,  554,
      553,  530,  553,  530,  530,  530,  554,  530,  554,    0,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530
    } ;

static yyconst flex_int16_t yy_nxt[921] =
    {   0,
      517,  496,   25,   26,   45,   46,   45,   46,   48,   49,
       60,   61,   48,   49,   52,   53,   27,   60,   61,   28,
       29,   30,   31,   32,   33,   52,   53,   34,   35,   35,
       50,   54,   55,   36,   36,  282,   37,   38,   39,   28,
       40,   42,   54,   55,   43,  530,   43,   43,   43,   43,
       63,   64,   56,  120,  121,  122,   57,  112,   43,   43,
       42,   58,   58,   43,   65,   43,   43,   43,   43,  203,
       56,   63,   64,  204,   57,   67,   68,   43,   43,   58,
       58,   67,   68,   71,   72,   65,   71,   72,  205,   69,
      256,   75,  112,   76,  204,   69,  123,   73,   77,  124,

       73,  229,  206,   78,   81,   82,   83,   84,  290,  230,
       95,   85,   96,   96,   96,  249,   86,   86,   88,   82,
       89,   90,  356,  259,  132,   91,   91,  530,  133,  166,
       92,   92,   97,  134,  134,  136,  112,  137,  137,  137,
      112,  212,   98,   99,  100,  101,  102,  103,  198,  104,
      105,  199,  106,  107,  108,  109,  110,  111,  112,  113,
      114,  115,  116,  117,  118,  119,   81,   82,   83,   84,
      264,  112,  154,   85,  155,  155,  155,  112,   86,   86,
       88,   82,   89,  150,  272,  265,  273,  151,   88,   82,
       89,   88,  152,  152,   95,  530,   96,   96,   96,   95,

      180,   96,   96,   96,  181,  494,  495,  189,  182,  112,
      159,  200,  160,  190,  183,  201,  191,  161,  146,  202,
      311,  192,  162,  163,  164,  164,  164,  149,  164,  312,
      283,  243,  284,  165,  112,  133,  193,  207,  112,  166,
      134,  134,  112,  212,  167,  168,  169,  112,  530,  112,
      136,  208,  137,  137,  137,  530,  209,  280,  170,  530,
      171,  172,  477,  173,  164,  164,  164,  112,  164,  189,
      112,  281,  257,  165,  530,  190,  530,  307,  191,  166,
      164,  164,  164,  174,  164,  530,  175,  297,  112,  165,
      276,  176,  112,  292,  177,  166,  112,  178,  277,  278,

      112,  285,  286,  179,  184,  287,  301,  112,  185,  186,
      327,  526,  187,  250,  136,  112,  137,  137,  137,  302,
      112,  530,  298,  112,  164,  164,  164,  154,  164,  155,
      155,  155,  154,  165,  155,  155,  155,  299,  316,  166,
      112,  259,  324,  300,  325,  317,  112,  166,  194,  530,
      112,  326,  192,  133,  375,  195,  196,  318,  134,  134,
      112,  197,  164,  164,  164,  112,  164,  255,  329,  330,
      331,  165,  334,  259,  335,  335,  335,  166,  112,  166,
      298,  210,  389,  379,  363,  380,  340,  418,  390,  403,
      404,  405,  334,  530,  335,  335,  335,  525,  211,  164,

      164,  164,  364,  164,  524,  530,  494,  495,  165,  439,
      248,  456,  457,  458,  166,  494,  495,  520,  213,  112,
      214,  511,  215,  522,  523,  528,  529,  522,  523,  112,
      216,  112,  217,  218,  522,  523,  112,  219,  220,  221,
      222,  223,  112,  112,  224,  225,  458,  226,  227,  236,
      237,  237,  528,  529,  112,  238,  238,  228,  112,  112,
      233,  234,  235,  528,  529,  236,  237,  237,  519,  112,
      112,  238,  238,   81,   82,   83,   84,  112,  518,  112,
       85,  516,  515,  514,  513,   86,   86,   24,   24,   24,
       41,   41,   41,   44,   44,   44,   47,   47,   47,   51,

       51,   51,   42,   42,   42,   59,   59,   59,   62,   62,
       62,   66,   66,   66,   70,   70,   70,   80,   80,   80,
      126,  512,  126,  138,  112,  138,  239,  487,  239,  258,
      258,  258,  336,  112,  336,  393,  393,  393,  486,  486,
      486,  493,  493,  493,  510,  510,  510,  521,  521,  521,
      527,  527,  527,  511,  509,  508,  507,  506,  505,  112,
      504,  503,  502,  112,  501,  112,  500,  112,  499,  498,
      112,  112,  112,  497,  492,  491,  490,  456,  489,  488,
      487,  112,  112,  112,  112,  485,  484,  483,  112,  112,
      482,  112,  481,  480,  479,  112,  112,  478,  112,  112,

      112,  112,  476,  475,  112,  474,  473,  472,  471,  112,
      470,  112,  112,  469,  468,  467,  112,  466,  465,  464,
      463,  462,  461,  460,  407,  459,  403,  112,  112,  112,
      112,  112,  455,  112,  112,  394,  454,  453,  452,  451,
      450,  112,  449,  448,  447,  446,  112,  445,  444,  443,
      442,  441,  440,  112,  438,  112,  437,  436,  112,  435,
      434,  433,  432,  431,  430,  429,  112,  428,  427,  426,
      425,  424,  423,  422,  421,  420,  419,  112,  112,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      333,  406,  329,  402,  401,  400,  112,  399,  398,  397,

      396,  395,  394,  392,  391,  112,  388,  387,  386,  385,
      384,  112,  112,  383,  382,  381,  378,  377,  376,  374,
      112,  112,  373,  372,  371,  370,  369,  368,  112,  367,
      366,  112,  365,  112,  362,  361,  360,  359,  358,  357,
      112,  112,  355,  354,  353,  352,  112,  351,  350,  349,
      348,  347,  112,  346,  345,  344,  112,  316,  290,  343,
      252,  253,  342,  341,  340,  339,  338,  337,  244,  333,
      332,  233,  112,  112,  328,  112,  323,  322,  321,  320,
      319,  315,  314,  313,  310,  309,  308,  306,  305,  304,
      303,  112,  296,  295,  294,  112,  293,  112,  291,  289,

      288,  112,  279,  275,  274,  271,  270,  269,  112,  268,
      267,  266,  263,  262,  261,  260,  166,  158,  254,  253,
      252,  153,  153,  251,  248,  250,  249,  248,  247,  246,
      245,  244,  135,  135,  242,  241,  240,  120,  232,  231,
      188,  158,   94,  157,   94,  156,   82,  153,   82,  149,
      148,  147,  146,  145,  144,  143,  142,  141,  140,  139,
      135,  131,  130,  129,  128,  127,  125,   94,   93,   87,
       79,   74,  530,   23,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,

      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530
    } ;

static yyconst flex_int16_t yy_chk[921] =
    {   0,
      552,  550,    1,    1,    5,    5,    6,    6,    7,    7,
       15,   15,    8,    8,    9,    9,    1,   16,   16,    1,
        1,    2,    2,    2,    2,   10,   10,    2,    2,    2,
        8,    9,    9,    2,    2,  188,    2,    2,    2,    2,
        2,    3,   10,   10,    3,  188,    3,    3,    3,    3,
       17,   17,   13,   38,   38,   38,   13,  526,    3,    3,
        4,   13,   13,    4,   17,    4,    4,    4,    4,  108,
       14,   18,   18,  108,   14,   19,   19,    4,    4,   14,
       14,   20,   20,   21,   21,   18,   22,   22,  109,   19,
      161,   27,  525,   27,  161,   20,   39,   21,   27,   39,

       22,  117,  109,   27,   30,   30,   30,   30,  193,  117,
       36,   30,   36,   36,   36,  193,   30,   30,   33,   33,
       33,   33,  277,  164,   56,   33,   33,  277,   56,  164,
       33,   33,   37,   56,   56,   58,  162,   58,   58,   58,
      162,  162,   37,   37,   37,   37,   37,   37,  106,   37,
       37,  106,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   81,   81,   81,   81,
      171,  175,   86,   81,   86,   86,   86,  175,   81,   81,
       84,   84,   84,   84,  180,  171,  180,   84,   88,   88,
       88,   88,   84,   84,   92,   97,   92,   92,   92,   96,

      100,   96,   96,   96,  100,  462,  462,  103,  100,  104,
       97,  107,   97,  103,  100,  107,  103,   97,  103,  107,
      215,  104,   97,   97,   98,   98,   98,  113,   98,  215,
      189,  132,  189,   98,  104,  132,  104,  110,  113,   98,
      132,  132,  113,  113,   98,   98,   98,  110,  433,  185,
      134,  110,  134,  134,  134,  163,  110,  185,   98,  116,
       98,   98,  433,   98,   99,   99,   99,  211,   99,  159,
      116,  187,  163,   99,  163,  159,  116,  211,  159,   99,
      112,  112,  112,   99,  112,  202,   99,  202,  187,  112,
      183,   99,  187,  196,   99,  112,  196,   99,  183,  183,

       99,  190,  190,   99,  101,  190,  206,  101,  101,  101,
      228,  519,  101,  203,  137,  101,  137,  137,  137,  206,
      203,  228,  203,  101,  105,  105,  105,  152,  105,  152,
      152,  152,  155,  105,  155,  155,  155,  204,  219,  105,
      160,  258,  226,  204,  227,  219,  220,  258,  105,  226,
      300,  227,  160,  243,  300,  105,  105,  220,  243,  243,
      220,  105,  111,  111,  111,  160,  111,  160,  235,  235,
      235,  111,  238,  259,  238,  238,  238,  111,  256,  259,
      256,  111,  316,  304,  284,  304,  341,  350,  316,  331,
      331,  331,  335,  350,  335,  335,  335,  518,  111,  114,

      114,  114,  284,  114,  517,  374,  493,  493,  114,  374,
      341,  405,  405,  405,  114,  495,  495,  514,  114,  512,
      114,  510,  114,  515,  515,  520,  520,  521,  521,  509,
      114,  508,  114,  114,  523,  523,  507,  114,  114,  114,
      115,  115,  506,  115,  115,  115,  458,  115,  115,  458,
      458,  458,  527,  527,  505,  458,  458,  115,  504,  115,
      122,  122,  122,  529,  529,  122,  122,  122,  503,  502,
      501,  122,  122,  253,  253,  253,  253,  500,  499,  498,
      253,  496,  492,  491,  490,  253,  253,  531,  531,  531,
      532,  532,  532,  533,  533,  533,  534,  534,  534,  535,

      535,  535,  536,  536,  536,  537,  537,  537,  538,  538,
      538,  539,  539,  539,  540,  540,  540,  541,  541,  541,
      542,  489,  542,  543,  488,  543,  544,  486,  544,  545,
      545,  545,  546,  485,  546,  547,  547,  547,  548,  548,
      548,  549,  549,  549,  551,  551,  551,  553,  553,  553,
      554,  554,  554,  484,  483,  482,  481,  480,  479,  478,
      477,  476,  475,  474,  473,  472,  471,  470,  469,  468,
      467,  466,  465,  464,  461,  460,  459,  457,  455,  454,
      453,  452,  451,  450,  449,  448,  447,  446,  445,  444,
      443,  442,  441,  440,  439,  438,  437,  436,  435,  434,

      432,  431,  430,  429,  428,  427,  426,  425,  424,  423,
      422,  421,  420,  419,  418,  417,  416,  415,  414,  412,
      411,  410,  409,  408,  407,  406,  404,  402,  401,  400,
      399,  398,  397,  396,  395,  393,  392,  391,  390,  389,
      388,  387,  386,  385,  384,  383,  382,  381,  380,  379,
      378,  377,  376,  375,  373,  372,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  349,  348,  347,
      346,  345,  344,  343,  342,  340,  339,  338,  337,  334,
      333,  332,  330,  328,  327,  326,  325,  324,  323,  322,

      321,  320,  319,  318,  317,  315,  314,  313,  312,  311,
      310,  309,  308,  307,  306,  305,  303,  302,  301,  299,
      298,  297,  296,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  286,  285,  283,  282,  281,  280,  279,  278,
      276,  275,  274,  273,  272,  271,  270,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  257,  255,  254,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  237,
      236,  234,  232,  231,  230,  229,  225,  224,  223,  222,
      221,  218,  217,  216,  214,  213,  212,  210,  209,  208,
      207,  205,  201,  200,  199,  198,  197,  195,  194,  192,

      191,  186,  184,  182,  181,  179,  178,  177,  176,  174,
      173,  172,  170,  169,  168,  167,  165,  158,  157,  156,
      154,  153,  151,  150,  149,  148,  147,  146,  145,  143,
      141,  136,  135,  133,  129,  125,  124,  121,  119,  118,
      102,   95,   94,   93,   91,   90,   89,   85,   83,   78,
       77,   76,   75,   73,   72,   69,   68,   65,   64,   61,
       57,   54,   53,   50,   49,   46,   40,   35,   34,   32,
       29,   26,   23,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,

      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "markdown.lex"
#line 2 "markdown.lex"

#include <string.h>
#include "blocknode.h"
#include "markdown.y.h"

#undef _ISDEBUGLEX

#ifdef _ISDEBUGLEX
#define P(token) fprintf(stdout, "token: %s: %s\n", token, yytext); BeginToken(yytext);
#else
#define P(token) BeginToken(yytext);
#endif

#define YY_INPUT(buf,result,max_size)  { \
    result = GetNextChar(buf, max_size); \
    if (  result <= 0  ) \
      result = YY_NULL; \
}

/* prototypes */
int yylineno;

/* input.c */
int GetNextChar(char *b, int maxBuffer);
void BeginToken(char *t);;

/* lexer states */


/* blankline ^[ ]{0,4}\r?\n */
#line 898 "markdown.lex.c"

#define INITIAL 0
#define ESCAPE 1
#define CODEBLOCK 2
#define XCODEBLOCK 3
#define CODESPAN 4
#define XCODESPAN 5
#define INDENTLIST 6
#define SHTMLBLOCK 7
#define SCRIPTBLOCK 8
#define STYLEBLOCK 9
#define SVGBLOCK 10

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 38 "markdown.lex"


    /* special chars: "\[]^-?.*+|()$/{}%<> */

#line 1098 "markdown.lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 531 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 874 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
goto find_rule; /* Shut up GCC warning -Wall */
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 42 "markdown.lex"
{ yylineno++; P("BLANKLINE"); return BLANKLINE; }
	YY_BREAK
/* !!! note: quoteblankline has no effect */
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 44 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 45 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 46 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 47 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 48 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "markdown.lex"
{ P("LARGERTHAN"); return LARGERTHAN; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 52 "markdown.lex"
{ P("SECTION"); 
                                            yylval.text = strdup(yytext);
                                            return SECTION; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "markdown.lex"
{ P("VSECTION"); 
                                            yylval.text = strdup(yytext);
                                            return VSECTION; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 60 "markdown.lex"
{ P("ESCAPE"); BEGIN ESCAPE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 61 "markdown.lex"
{ BEGIN INITIAL; yylval.text = strdup(yytext); P("SPECIALCHAR"); return SPECIALCHAR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 62 "markdown.lex"
{ BEGIN INITIAL; yylval.text = strdup(yytext); P("SPECIALCHAR"); return SPECIALCHAR; }
	YY_BREAK
/* backtick only support single line mode */
case 13:
YY_RULE_SETUP
#line 65 "markdown.lex"
{ P("BACKTICK"); BEGIN CODESPAN; yylval.text = strdup(yytext); return BACKTICK; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 66 "markdown.lex"
{ P("SPECIALCHAR"); 
                                            yylval.text = strdup("`"); return SPECIALCHAR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 68 "markdown.lex"
{ P("CODETEXT"); yylval.text = strdup(yytext); return CODETEXT; }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 69 "markdown.lex"
{ P("LINEBREAK"); BEGIN INITIAL; yylval.text = strdup(yytext); return LINEBREAK; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "markdown.lex"
{ P("BACKTICK"); BEGIN INITIAL; yylval.text = strdup(yytext); return BACKTICK; }
	YY_BREAK
/* double-backtick will be teated as plain text */
case 18:
YY_RULE_SETUP
#line 73 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 75 "markdown.lex"
{ P("TRIPLEBACKTICK"); BEGIN XCODEBLOCK; yylval.text = strdup(yytext); return TRIPLEBACKTICK; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 76 "markdown.lex"
{ P("CODETEXT"); yylval.text = strdup(yytext); return CODETEXT; }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 77 "markdown.lex"
{ P("CODETEXT"); yylval.text = strdup(yytext);
                                           yylineno++; return CODETEXT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 79 "markdown.lex"
{ P("TRIPLEBACKTICK"); BEGIN INITIAL; yylval.text = strdup(yytext); return TRIPLEBACKTICK; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 83 "markdown.lex"
{ P("ULSTART"); return ULSTART; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 84 "markdown.lex"
{ P("QUOTEULSTART"); return QUOTEULSTART; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 85 "markdown.lex"
{ P("OLSTART"); return OLSTART; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 86 "markdown.lex"
{ P("QUOTEOLSTART"); return QUOTEOLSTART; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 90 "markdown.lex"
{ 
                                            /* indent ul list */
                                            if(is_in_list(indent_level(yytext))){
                                                BEGIN INDENTLIST;
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT; 
                                            }
                                            else{
                                                BEGIN CODEBLOCK; 
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT;
                                            }
                                        }   
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 103 "markdown.lex"
{ 
                                            /* indent ol list */
                                            if(is_in_list(indent_level(yytext))){
                                                BEGIN INDENTLIST;
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT; 
                                            }
                                            else{
                                                BEGIN CODEBLOCK; 
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT;
                                            }
                                        }   
	YY_BREAK
case 29:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 116 "markdown.lex"
{ 
                                            /* indent p */
                                            if(is_in_list(indent_level(yytext))){
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT; 
                                            }
                                            else{
                                                BEGIN CODEBLOCK; 
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT;
                                            }
                                        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 128 "markdown.lex"
{ yylval.text = strdup(yytext); P("CODETEXT"); return CODETEXT; }
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 129 "markdown.lex"
{ P(""); BEGIN INITIAL; yylineno++; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 131 "markdown.lex"
{ BEGIN INITIAL; P("ULSTART"); return ULSTART; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 132 "markdown.lex"
{ BEGIN INITIAL; P("OLSTART"); return OLSTART; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 135 "markdown.lex"
{ yylval.text = strdup(yytext); P("H"); return H; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 136 "markdown.lex"
{ yylval.text = strdup(yytext); P("QUOTEH"); return QUOTEH; }
	YY_BREAK
/* block and functional html tags must be in one line and must start at first column */
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 139 "markdown.lex"
{ 
                                            yylval.text = strdup(yytext); 
                                            P("HTMLBLOCK"); 
                                            BEGIN SHTMLBLOCK; 
                                            return HTMLBLOCK; 
                                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 145 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 146 "markdown.lex"
{ yylineno++; P("LINEBREAK"); BEGIN INITIAL;  return LINEBREAK; }
	YY_BREAK
/* linkable text */
case 39:
YY_RULE_SETUP
#line 149 "markdown.lex"
{
                                            yylval.text = strdup(yytext);
                                            P("LINK");
                                            return LINK;
                                        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 154 "markdown.lex"
{
                                            yylval.text = strdup(yytext);
                                            P("LINK");
                                            return LINK;
                                        }
	YY_BREAK
/* script block */
/* problem triggered below: input buffer overflow, can't enlarge buffer because scanner uses REJECT */
/*^\<script[^>]*>/(.|[\r\n])*\<\/script>  { */
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 166 "markdown.lex"
{
                                            BEGIN SCRIPTBLOCK; 
                                            yylval.text = strdup(yytext); 
                                            P("SCRIPTSTART"); 
                                            return SCRIPTSTART; 
                                        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 172 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 173 "markdown.lex"
{ 
                                            yylineno++; 
                                            yylval.text = strdup(yytext); 
                                            P("TEXT"); 
                                            return TEXT; 
                                        }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 179 "markdown.lex"
{ 
                                            BEGIN INITIAL; 
                                            yylval.text = strdup("</script>"); 
                                            P("SCRIPTEND"); 
                                            return SCRIPTEND;
                                        }
	YY_BREAK
/* style block */
/* ^\<style[^>]*>/(.|[\r\n])*\<\/style>    { */
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 192 "markdown.lex"
{
                                            yylval.text = strdup(yytext); 
                                            P("STYLESTART"); 
                                            BEGIN STYLEBLOCK; 
                                            return STYLESTART; 
                                        }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 198 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 199 "markdown.lex"
{ 
                                            yylineno++; 
                                            yylval.text = strdup(yytext); 
                                            P("TEXT"); 
                                            return TEXT; 
                                        }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 205 "markdown.lex"
{ 
                                            yylval.text = "</style>"; 
                                            P("STYLEEND"); 
                                            BEGIN INITIAL; 
                                            return STYLEEND;
                                        }
	YY_BREAK
/* svg block */
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 215 "markdown.lex"
{
                                            yylval.text = strdup(yytext); 
                                            P("SVGSTART"); 
                                            BEGIN SVGBLOCK; 
                                            return SVGSTART; 
                                        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 221 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 222 "markdown.lex"
{ 
                                            yylineno++; 
                                            yylval.text = strdup(yytext); 
                                            P("TEXT"); 
                                            return TEXT; 
                                        }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 228 "markdown.lex"
{ 
                                            yylval.text = "</svg>"; 
                                            P("SVGEND"); 
                                            BEGIN INITIAL; 
                                            return SVGEND;
                                        }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 239 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 240 "markdown.lex"
{ yylineno++; P("LINEBREAK"); return LINEBREAK; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 243 "markdown.lex"
ECHO;
	YY_BREAK
#line 1621 "markdown.lex.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(ESCAPE):
			case YY_STATE_EOF(CODEBLOCK):
			case YY_STATE_EOF(XCODEBLOCK):
			case YY_STATE_EOF(CODESPAN):
			case YY_STATE_EOF(XCODESPAN):
			case YY_STATE_EOF(INDENTLIST):
			case YY_STATE_EOF(SHTMLBLOCK):
			case YY_STATE_EOF(SCRIPTBLOCK):
			case YY_STATE_EOF(STYLEBLOCK):
			case YY_STATE_EOF(SVGBLOCK):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 531 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 531 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 530);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 243 "markdown.lex"



int yywrap(){
    return 1;
}


    /*
    int main(int argc, char **argv){
        yyin = fopen(argv[1], "r");
        yylex();
        fclose(yyin);
    }
    */




