#line 2 "markdown.lex.c"

#line 4 "markdown.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 53
#define YY_END_OF_BUFFER 54
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[165] =
    {   0,
       54,   51,   53,   52,   53,   51,   53,   51,   53,   10,
       51,   53,   13,   51,   53,   51,   53,16410,16411,    1,
       52,   53,   51,   53,   51,   53,   33,   51,   53,   51,
       53,   51,   53,   51,   53,    7,   51,   53,   51,   53,
       12,   53,   53,   11,   12,   53,   29,   53,   30,   53,
       29,   53,   15,   53,   16,   53,   53,   16,   53,   17,
       53,   19,   53,   20,   53,   19,   53,   19,   53,   53,
       53,   53,   36,   53,   37,   53,   36,   53,   40,   53,
       41,   53,   53,   40,   53,   44,   53,   45,   53,   44,
       53,   44,   53,   48,   53,   49,   53,   48,   53,   48,

       53,   52,   18,   28,   28,16410,16411,    1,   28,   28,
       28,   28,    1,   52,   33,   22,    2,    8,   29,   30,
       15,   16,   14,   20,   21,   31,   36,   37,   41,   45,
       49, 8218,   33,   24,   35,    3,   34,    8,    9,   32,
     8219,16410,16411,   33,    4,   34,   23,    9,   33,   47,
        5,   34,   25,   33,    6,   34,   43,   34,   50,   39,
       34,   38,   46,   42
    } ;

static yyconst flex_int16_t yy_accept[520] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    6,    8,   10,   13,   16,   20,   23,
       25,   27,   30,   32,   34,   36,   39,   41,   43,   44,
       47,   49,   51,   53,   55,   57,   58,   60,   62,   64,
       66,   68,   70,   71,   72,   73,   75,   77,   79,   81,
       83,   84,   86,   88,   90,   92,   94,   96,   98,  100,
      102,  103,  103,  103,  103,  104,  105,  108,  109,  110,
      111,  112,  113,  115,  115,  115,  115,  115,  115,  116,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,

      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  118,  118,  118,  119,
      119,  120,  121,  122,  123,  124,  125,  126,  126,  126,
      126,  127,  127,  127,  128,  129,  130,  130,  131,  131,
      132,  132,  132,  132,  132,  132,  132,  132,  133,  133,
      133,  133,  134,  135,  135,  135,  135,  135,  135,  135,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,

      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  137,  137,  137,
      138,  138,  138,  139,  140,  140,  141,  141,  141,  141,
      141,  141,  141,  141,  142,  144,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,

      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  146,  146,  146,  147,  148,  148,  148,  149,  149,
      149,  149,  149,  149,  149,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  151,  151,  151,  151,
      151,  151,  151,  151,  151,  152,  152,  152,  153,  154,

      154,  154,  154,  154,  154,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  156,  156,
      156,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  158,  158,
      158,  159,  159,  159,  159,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,

      160,  161,  161,  162,  162,  162,  163,  163,  163,  163,
      163,  164,  164,  164,  164,  164,  165,  165,  165
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    1,    1,    1,    6,
        6,    9,    9,    1,   10,   11,   12,   13,   14,   14,
       14,   14,   14,   14,   15,   15,   15,   16,    1,   17,
        1,   18,    1,   19,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   20,    1,    1,    6,   21,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,    1,    6,    1,    6,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    1,    5,
        5,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[543] =
    {   0,
        0,   20,   39,   58,    2,    4,    6,   11,   15,   49,
       66,   68,    8,   40,   59,   81,   83,   85,   87,   89,
      911,  912,  912,  907,   67,  912,  888,  105,  912,  905,
      119,  899,  901,   43,  123,  108,   75,  912,  912,  912,
        0,  912,  902,    0,  912,  901,  882,  912,  912,  912,
      899,  880,  122,  895,  127,    0,  912,  896,  912,  912,
      895,  885,  912,  912,  893,  883,  912,  912,  891,  881,
      912,  851,  850,  868,  912,  912,  167,  912,  886,  181,
      883,  164,  912,  189,  884,  881,  880,  186,  876,  878,
      877,  191,  186,  224,  264,  181,  285,  847,  180,   91,

      324,  128,   73,   29,  103,  201,  362,  247,  181,  399,
      421,  223,  158,  857,  845,  912,  875,  460,    0,  837,
        0,  912,    0,  912,  912,  912,  912,  265,  871,  226,
      870,  869,  270,    0,  912,  912,  833,  912,  832,  912,
      831,  833,  828,  838,  862,  861,  277,  860,  859,  306,
      858,  854,  856,  257,  299,  186,  234,  260,  842,  912,
      836,  819,  832,  819,  148,  825,  829,  813,  265,  824,
      815,  825,  808,   37,  813,  806,  289,  805,  192,  810,
      294,   93,  204,  263,  822,  821,  212,  803,  813,  220,
      810,  814,  792,  814,  808,  297,  304,  304,  792,    6,

      803,  792,  791,  792,  318,  807,  795,  789,  211,  805,
      784,  803,  307,  326,  796,  800,  786,  776,  784,  322,
      316,  302,  780,  793,  778,  779,  912,  812,  367,  806,
      808,  362,    0,    0,  347,  807,  787,  769,  766,  792,
      770,  773,  800,  799,  474,  795,  768,  342,  762,  370,
      371,  761,  763,  759,  764,  774,  765,  769,  763,  766,
      767,  744,  748,  745,  746,  745,  759,  758,  181,  749,
      760,  759,  747,  753,  745,  231,  736,  735,  741,  740,
      748,  739,  749,  728,  734,  740,  741,  740,  733,  732,
      721,  282,  723,  737,  734,  357,  722,  736,  729,  710,

      718,  724,  712,  726,  718,  711,  714,  356,  715,  713,
      728,  712,  719,  702,  706,  719,  714,  706,  714,  711,
      912,  733,  390,  727,  729,  728,  385,    0,  693,  685,
      702,  717,  374,  687,  719,  691,  699,  698,  699,  696,
      685,  364,  688,  683,  696,  687,  690,  676,  692,  680,
      682,  675,  685,  684,  686,  668,  680,  679,  678,  669,
      661,  676,  674,  666,  663,  279,  658,  674,  656,  670,
      654,  656,  649,  656,  650,  651,  657,  662,  652,  660,
      651,  647,  655,  658,  661,  912,  652,  631,  654,  634,
      649,  647,  640,  635,  912,  667,  404,  661,  663,  637,

      633,  647,  652,  627,  912,  616,  621,  619,  626,  622,
      619,  621,  615,  618,  614,  616,  616,  620,  616,  620,
      607,  609,  619,  605,  147,  604,  616,  615,  605,  614,
      597,  603,  606,  594,  598,  598,  591,  605,  589,  593,
      587,  601,  600,  597,  606,  584,  583,  912,  618,  444,
      612,  582,  592,  140,    0,  583,  576,  589,  579,  571,
      577,  569,  585,  569,  552,  565,  549,  544,  515,  529,
      526,  514,  504,  447,  468,  450,  466,  912,  436,  455,
      472,  432,  454,  409,  912,  412,  453,  426,  430,  424,
      416,  404,  409,  393,  398,  384,  381,  383,  370,  387,

      912,  356,  912,  350,  415,  912,  311,  311,  423,  425,
      912,  427,   71,   30,  434,  912,  452,  912,  489,  494,
      499,  504,  509,  514,  519,  524,  529,  534,  539,  544,
      549,  553,  558,  563,  568,  573,  578,  583,  588,  593,
      598,  603
    } ;

static yyconst flex_int16_t yy_def[543] =
    {   0,
      519,  519,  520,  520,  521,  521,  522,  522,  523,  523,
      524,  524,  525,  525,  526,  526,  527,  527,  528,  528,
      518,  518,  518,  518,  518,  518,  518,  529,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      530,  518,  530,  531,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  532,  518,  532,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  529,  518,  518,  518,
      518,  518,  518,  518,  518,   31,  518,  518,  518,  518,
      518,  518,   35,  518,  518,  518,  518,  518,  518,  518,

      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  107,  518,  518,  518,  518,  518,  518,  533,  518,
      530,  518,  531,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  532,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,   80,  518,  518,  518,  518,  518,
       31,  518,  518,  518,  518,  518,  110,  534,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  112,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  112,  518,  518,  518,  518,

      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  112,
      518,  112,  518,  518,  518,  518,  518,  518,  118,  518,
      518,  518,  533,  535,  518,  518,  518,  518,  518,  518,
      518,  518,   80,  518,  529,  518,  518,  518,  518,  534,
      534,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  112,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,

      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      536,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  118,  518,  518,  518,  518,  535,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  112,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  220,  518,
      518,  518,  518,  518,  518,  220,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  536,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  118,  518,  518,  518,

      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  220,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  537,  518,  518,  518,  518,  518,
      518,  518,  518,  538,  539,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  540,  518,  537,  518,  518,  518,
      518,  518,  518,  538,  518,  538,  539,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  540,

      518,  518,  518,  518,  541,  518,  518,  518,  542,  541,
      518,  541,  518,  518,  542,  518,  542,    0,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518
    } ;

static yyconst flex_int16_t yy_nxt[959] =
    {   0,
      518,  518,   23,   24,   42,   43,   42,   43,   45,   46,
       57,   58,  518,   45,   46,  518,   25,   50,   51,   26,
       27,   28,   29,   30,   31,   47,   48,   32,   33,   33,
       47,   48,  293,   34,   34,   52,   35,   36,   37,   26,
       27,   39,   57,   58,   40,  294,   40,   40,   40,   40,
      197,   50,   51,   91,  198,   92,   92,   92,   40,   40,
       39,   60,   61,   40,  108,   40,   40,   40,   40,   52,
       53,  264,   53,  265,   54,   62,   54,   40,   40,   55,
       55,   55,   55,   60,   61,   64,   65,   64,   65,   68,
       69,   68,   69,   72,  194,   73,  108,   62,  195,   66,

       74,   66,  196,   70,  108,   70,   77,   78,   79,   80,
      116,  117,  118,   81,  119,  274,  186,  120,   82,   82,
       84,   78,   85,   86,  199,  518,  128,   87,   87,  108,
      129,  187,   88,   88,   93,  130,  130,  132,  200,  133,
      133,  133,  485,  486,   94,   95,   96,   97,   98,   99,
      192,  100,  101,  193,  102,  103,  104,  105,  106,  107,
      108,  109,  110,  111,  112,  113,  114,  115,   77,   78,
       79,   80,  518,  256,  149,   81,  150,  150,  150,  223,
       82,   82,   84,   78,   85,  145,  468,  224,  257,  146,
       84,   78,   85,   84,  147,  147,   91,  518,   92,   92,

       92,   91,  174,   92,   92,   92,  175,  248,  348,  183,
      176,  198,  154,  518,  155,  184,  177,  108,  185,  156,
      142,  108,  206,  201,  108,  157,  158,  158,  158,  275,
      158,  276,  272,  108,  303,  159,  132,  202,  133,  133,
      133,  160,  203,  304,  518,  282,  161,  162,  163,  158,
      158,  158,  241,  158,  355,  108,  284,  518,  159,  108,
      164,  518,  165,  166,  160,  167,  158,  158,  158,  235,
      158,  251,  356,  129,  249,  159,  518,  160,  130,  130,
      132,  160,  133,  133,  133,  168,  183,  149,  169,  150,
      150,  150,  184,  170,  108,  185,  171,  277,  278,  172,

      108,  279,  108,  108,  518,  173,  178,  367,  431,  108,
      179,  180,  108,  268,  181,  273,  149,  108,  150,  150,
      150,  269,  270,  319,  186,  108,  158,  158,  158,  518,
      158,  289,  108,  242,  518,  159,  108,  108,  291,  247,
      108,  160,  290,  108,  292,  308,  514,  316,  108,  317,
      188,  513,  309,  299,  518,  129,  318,  189,  190,  310,
      130,  130,  108,  191,  158,  158,  158,  509,  158,  321,
      322,  323,  326,  159,  327,  327,  327,  108,  108,  160,
      290,  251,  251,  204,  371,  381,  372,  160,  160,  332,
      410,  382,  395,  396,  397,  326,  518,  327,  327,  327,

      205,  158,  158,  158,  501,  158,  448,  449,  450,  108,
      159,  485,  486,  240,  485,  486,  160,  511,  512,  108,
      207,  108,  208,  108,  209,  516,  517,  511,  512,  511,
      512,  108,  210,  108,  211,  212,  516,  517,  508,  213,
      214,  215,  216,  217,  108,  108,  218,  219,  450,  220,
      221,  230,  231,  231,  516,  517,  108,  232,  232,  222,
      108,  108,  227,  228,  229,  507,  108,  230,  231,  231,
      506,  505,  504,  232,  232,   77,   78,   79,   80,  503,
      502,  108,   81,  478,  108,  501,  499,   82,   82,   22,
       22,   22,   22,   22,   38,   38,   38,   38,   38,   41,

       41,   41,   41,   41,   44,   44,   44,   44,   44,   49,
       49,   49,   49,   49,   39,   39,   39,   39,   39,   56,
       56,   56,   56,   56,   59,   59,   59,   59,   59,   63,
       63,   63,   63,   63,   67,   67,   67,   67,   67,   76,
       76,   76,   76,   76,  121,  498,  121,  121,  121,  123,
      497,  496,  123,  134,  495,  134,  134,  134,  233,  108,
      233,  233,  233,  250,  250,  250,  250,  250,  328,  494,
      328,  328,  328,  385,  385,  385,  385,  385,  477,  477,
      477,  477,  477,  484,  484,  484,  484,  484,  487,  493,
      492,  108,  487,  500,  500,  500,  500,  500,  510,  510,

      510,  510,  510,  515,  515,  515,  515,  515,  491,  108,
      490,  108,  489,  488,  108,  108,  108,  483,  482,  481,
      448,  480,  479,  478,  108,  108,  108,  108,  476,  475,
      474,  108,  108,  473,  108,  472,  471,  470,  108,  108,
      469,  108,  108,  108,  108,  467,  466,  108,  465,  464,
      463,  462,  108,  461,  108,  108,  460,  459,  458,  108,
      457,  456,  240,  455,  454,  453,  452,  399,  451,  395,
      108,  108,  108,  108,  108,  447,  108,  108,  386,  446,
      445,  444,  443,  442,  108,  441,  440,  439,  438,  108,
      437,  436,  435,  434,  433,  432,  108,  430,  108,  429,

      428,  108,  427,  426,  425,  424,  423,  422,  421,  108,
      420,  419,  418,  417,  416,  415,  414,  413,  412,  411,
      108,  108,  409,  408,  407,  406,  405,  404,  403,  402,
      401,  400,  399,  325,  398,  321,  394,  393,  392,  108,
      391,  390,  389,  388,  387,  386,  384,  383,  108,  380,
      379,  378,  377,  376,  108,  108,  375,  374,  373,  370,
      369,  368,  366,  108,  108,  365,  364,  363,  362,  361,
      360,  108,  359,  358,  108,  357,  108,  354,  353,  352,
      351,  350,  349,  108,  108,  347,  346,  345,  344,  108,
      343,  342,  341,  340,  339,  108,  338,  337,  336,  108,

      308,  282,  335,  244,  245,  334,  333,  332,  331,  330,
      329,  236,  325,  324,  227,  108,  108,  320,  108,  315,
      314,  313,  312,  311,  307,  306,  305,  302,  301,  300,
      298,  297,  296,  295,  108,  288,  287,  286,  108,  285,
      108,  283,  281,  280,  108,  271,  267,  266,  263,  262,
      261,  108,  260,  259,  258,  255,  254,  253,  252,  160,
      153,  246,  245,  244,  148,  148,  243,  242,  241,  240,
      239,  238,  237,  236,  131,  131,  234,  116,  226,  225,
      182,  153,   90,  152,   90,  151,   78,  148,   78,  144,
      143,  142,  141,  140,  139,  138,  137,  136,  135,  131,

      127,  126,  125,  124,  122,   90,   89,   83,   75,   71,
      518,   21,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518
    } ;

static yyconst flex_int16_t yy_chk[959] =
    {   0,
        0,    0,    1,    1,    5,    5,    6,    6,    7,    7,
       13,   13,    0,    8,    8,    0,    1,    9,    9,    1,
        1,    2,    2,    2,    2,    7,    7,    2,    2,    2,
        8,    8,  200,    2,    2,    9,    2,    2,    2,    2,
        2,    3,   14,   14,    3,  200,    3,    3,    3,    3,
      104,   10,   10,   34,  104,   34,   34,   34,    3,    3,
        4,   15,   15,    4,  514,    4,    4,    4,    4,   10,
       11,  174,   12,  174,   11,   15,   12,    4,    4,   11,
       11,   12,   12,   16,   16,   17,   17,   18,   18,   19,
       19,   20,   20,   25,  103,   25,  513,   16,  103,   17,

       25,   18,  103,   19,  100,   20,   28,   28,   28,   28,
       36,   36,   36,   28,   37,  182,  100,   37,   28,   28,
       31,   31,   31,   31,  105,  182,   53,   31,   31,  100,
       53,  100,   31,   31,   35,   53,   53,   55,  105,   55,
       55,   55,  454,  454,   35,   35,   35,   35,   35,   35,
      102,   35,   35,  102,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   77,   77,
       77,   77,  425,  165,   82,   77,   82,   82,   82,  113,
       77,   77,   80,   80,   80,   80,  425,  113,  165,   80,
       84,   84,   84,   84,   80,   80,   88,   93,   88,   88,

       88,   92,   96,   92,   92,   92,   96,  156,  269,   99,
       96,  156,   93,  269,   93,   99,   96,  109,   99,   93,
       99,  109,  109,  106,  179,   93,   94,   94,   94,  183,
       94,  183,  179,  106,  209,   94,  130,  106,  130,  130,
      130,   94,  106,  209,  112,  187,   94,   94,   94,  108,
      108,  108,  187,  108,  276,  112,  190,  157,  108,  190,
       94,  112,   94,   94,  108,   94,   95,   95,   95,  128,
       95,  158,  276,  128,  157,   95,  157,  158,  128,  128,
      133,   95,  133,  133,  133,   95,  154,  147,   95,  147,
      147,  147,  154,   95,  169,  154,   95,  184,  184,   95,

      169,  184,   95,  292,  366,   95,   97,  292,  366,   97,
       97,   97,  155,  177,   97,  181,  150,   97,  150,  150,
      150,  177,  177,  222,  155,   97,  101,  101,  101,  196,
      101,  196,  181,  197,  222,  101,  181,  155,  198,  155,
      197,  101,  197,  205,  198,  213,  508,  220,  214,  221,
      101,  507,  213,  205,  220,  235,  221,  101,  101,  214,
      235,  235,  214,  101,  107,  107,  107,  504,  107,  229,
      229,  229,  232,  107,  232,  232,  232,  502,  248,  107,
      248,  250,  251,  107,  296,  308,  296,  250,  251,  333,
      342,  308,  323,  323,  323,  327,  342,  327,  327,  327,

      107,  110,  110,  110,  500,  110,  397,  397,  397,  499,
      110,  484,  484,  333,  486,  486,  110,  505,  505,  498,
      110,  497,  110,  496,  110,  509,  509,  510,  510,  512,
      512,  495,  110,  494,  110,  110,  515,  515,  493,  110,
      110,  110,  111,  111,  492,  111,  111,  111,  450,  111,
      111,  450,  450,  450,  517,  517,  491,  450,  450,  111,
      490,  111,  118,  118,  118,  489,  488,  118,  118,  118,
      487,  483,  482,  118,  118,  245,  245,  245,  245,  481,
      480,  479,  245,  477,  476,  475,  474,  245,  245,  519,
      519,  519,  519,  519,  520,  520,  520,  520,  520,  521,

      521,  521,  521,  521,  522,  522,  522,  522,  522,  523,
      523,  523,  523,  523,  524,  524,  524,  524,  524,  525,
      525,  525,  525,  525,  526,  526,  526,  526,  526,  527,
      527,  527,  527,  527,  528,  528,  528,  528,  528,  529,
      529,  529,  529,  529,  530,  473,  530,  530,  530,  531,
      472,  471,  531,  532,  470,  532,  532,  532,  533,  469,
      533,  533,  533,  534,  534,  534,  534,  534,  535,  468,
      535,  535,  535,  536,  536,  536,  536,  536,  537,  537,
      537,  537,  537,  538,  538,  538,  538,  538,  539,  467,
      466,  465,  539,  540,  540,  540,  540,  540,  541,  541,

      541,  541,  541,  542,  542,  542,  542,  542,  464,  463,
      462,  461,  460,  459,  458,  457,  456,  453,  452,  451,
      449,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  424,  423,  422,  421,  420,  419,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      407,  406,  404,  403,  402,  401,  400,  399,  398,  396,
      394,  393,  392,  391,  390,  389,  388,  387,  385,  384,
      383,  382,  381,  380,  379,  378,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  368,  367,  365,  364,  363,

      362,  361,  360,  359,  358,  357,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  347,  346,  345,  344,  343,
      341,  340,  339,  338,  337,  336,  335,  334,  332,  331,
      330,  329,  326,  325,  324,  322,  320,  319,  318,  317,
      316,  315,  314,  313,  312,  311,  310,  309,  307,  306,
      305,  304,  303,  302,  301,  300,  299,  298,  297,  295,
      294,  293,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  275,  274,  273,
      272,  271,  270,  268,  267,  266,  265,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,

      249,  247,  246,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  231,  230,  228,  226,  225,  224,  223,  219,
      218,  217,  216,  215,  212,  211,  210,  208,  207,  206,
      204,  203,  202,  201,  199,  195,  194,  193,  192,  191,
      189,  188,  186,  185,  180,  178,  176,  175,  173,  172,
      171,  170,  168,  167,  166,  164,  163,  162,  161,  159,
      153,  152,  151,  149,  148,  146,  145,  144,  143,  142,
      141,  139,  137,  132,  131,  129,  120,  117,  115,  114,
       98,   91,   90,   89,   87,   86,   85,   81,   79,   74,
       73,   72,   70,   69,   66,   65,   62,   61,   58,   54,

       52,   51,   47,   46,   43,   33,   32,   30,   27,   24,
       21,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "markdown.lex"
#line 2 "markdown.lex"

#include <string.h>
#include "blocknode.h"
#include "markdown.y.h"

#undef _ISDEBUGLEX

#ifdef _ISDEBUGLEX
#define P(token) fprintf(stdout, "token: %s\n", token); BeginToken(yytext);
#else
#define P(token) BeginToken(yytext);
#endif

#define YY_INPUT(buf,result,max_size)  { \
    result = GetNextChar(buf, max_size); \
    if (  result <= 0  ) \
      result = YY_NULL; \
}

/* prototypes */
int yylineno;

/* input.c */
int GetNextChar(char *b, int maxBuffer);
void BeginToken(char *t);;

 

/* blankline ^[ ]{0,4}\r?\n */
#line 901 "markdown.lex.c"

#define INITIAL 0
#define ESCAPE 1
#define CODEBLOCK 2
#define CODESPAN 3
#define XCODESPAN 4
#define INDENTLIST 5
#define SHTMLBLOCK 6
#define SCRIPTBLOCK 7
#define STYLEBLOCK 8
#define SVGBLOCK 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 37 "markdown.lex"


    /* special chars: "\[]^-?.*+|()$/{}%<> */

#line 1100 "markdown.lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 519 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 912 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
goto find_rule; /* Shut up GCC warning -Wall */
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 41 "markdown.lex"
{ yylineno++; P("BLANKLINE"); return BLANKLINE; }
	YY_BREAK
/* !!! note: quoteblankline has no effect */
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 43 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 44 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 45 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 46 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 47 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "markdown.lex"
{ P("LARGERTHAN"); return LARGERTHAN; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 "markdown.lex"
{ P("SECTION"); 
                                            yylval.text = strdup(yytext);
                                            return SECTION; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 54 "markdown.lex"
{ P("VSECTION"); 
                                            yylval.text = strdup(yytext);
                                            return VSECTION; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "markdown.lex"
{ P("ESCAPE"); BEGIN ESCAPE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "markdown.lex"
{ BEGIN INITIAL; yylval.text = strdup(yytext); P("SPECIALCHAR"); return SPECIALCHAR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 61 "markdown.lex"
{ BEGIN INITIAL; yylval.text = strdup(yytext); P("SPECIALCHAR"); return SPECIALCHAR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "markdown.lex"
{ P("BACKTICK"); BEGIN CODESPAN; return BACKTICK; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "markdown.lex"
{ P("SPECIALCHAR"); 
                                            yylval.text = strdup("`"); return SPECIALCHAR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 "markdown.lex"
{ P("CODETEXT"); yylval.text = strdup(yytext); return CODETEXT; }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 67 "markdown.lex"
{ P("CODETEXT"); yylval.text = strdup(yytext); 
                                            yylineno++; return CODETEXT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 69 "markdown.lex"
{ P("BACKTICK"); BEGIN INITIAL; return BACKTICK; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "markdown.lex"
{ P("DOUBLEBACKTICK"); BEGIN XCODESPAN; return DOUBLEBACKTICK; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "markdown.lex"
{ P("CODETEXT"); yylval.text = strdup(yytext); return CODETEXT; }
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 73 "markdown.lex"
{ P("CODETEXT"); yylval.text = strdup(yytext);
                                            yylineno++; return CODETEXT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 75 "markdown.lex"
{ P("DOUBLEBACKTICK"); BEGIN INITIAL; return DOUBLEBACKTICK; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 79 "markdown.lex"
{ P("ULSTART"); return ULSTART; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 80 "markdown.lex"
{ P("QUOTEULSTART"); return QUOTEULSTART; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 81 "markdown.lex"
{ P("OLSTART"); return OLSTART; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 82 "markdown.lex"
{ P("QUOTEOLSTART"); return QUOTEOLSTART; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 86 "markdown.lex"
{ 
                                            /* indent ul list */
                                            if(is_in_list(indent_level(yytext))){
                                                BEGIN INDENTLIST;
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT; 
                                            }
                                            else{
                                                BEGIN CODEBLOCK; 
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT;
                                            }
                                        }   
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 99 "markdown.lex"
{ 
                                            /* indent ol list */
                                            if(is_in_list(indent_level(yytext))){
                                                BEGIN INDENTLIST;
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT; 
                                            }
                                            else{
                                                BEGIN CODEBLOCK; 
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT;
                                            }
                                        }   
	YY_BREAK
case 28:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 112 "markdown.lex"
{ 
                                            /* indent p */
                                            if(is_in_list(indent_level(yytext))){
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT; 
                                            }
                                            else{
                                                BEGIN CODEBLOCK; 
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT;
                                            }
                                        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 124 "markdown.lex"
{ yylval.text = strdup(yytext); P("CODETEXT"); return CODETEXT; }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 125 "markdown.lex"
{ P(""); BEGIN INITIAL; yylineno++; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 127 "markdown.lex"
{ BEGIN INITIAL; P("ULSTART"); return ULSTART; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 128 "markdown.lex"
{ BEGIN INITIAL; P("OLSTART"); return OLSTART; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 131 "markdown.lex"
{ yylval.text = strdup(yytext); P("H"); return H; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 132 "markdown.lex"
{ yylval.text = strdup(yytext); P("QUOTEH"); return QUOTEH; }
	YY_BREAK
/* block and functional html tags must be in one line and must start at first column */
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 135 "markdown.lex"
{ 
                                            yylval.text = strdup(yytext); 
                                            P("HTMLBLOCK"); 
                                            BEGIN SHTMLBLOCK; 
                                            return HTMLBLOCK; 
                                        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 141 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 142 "markdown.lex"
{ yylineno++; P("LINEBREAK"); BEGIN INITIAL;  return LINEBREAK; }
	YY_BREAK
/* linkable text */
case 38:
YY_RULE_SETUP
#line 145 "markdown.lex"
{
                                            yylval.text = strdup(yytext);
                                            P("LINK");
                                            return LINK;
                                        }
	YY_BREAK
/* script block */
/* problem triggered below: input buffer overflow, can't enlarge buffer because scanner uses REJECT */
/*^\<script[^>]*>/(.|[\r\n])*\<\/script>  { */
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 157 "markdown.lex"
{
                                            BEGIN SCRIPTBLOCK; 
                                            yylval.text = strdup(yytext); 
                                            P("SCRIPTSTART"); 
                                            return SCRIPTSTART; 
                                        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 163 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 164 "markdown.lex"
{ 
                                            yylineno++; 
                                            yylval.text = strdup(yytext); 
                                            P("TEXT"); 
                                            return TEXT; 
                                        }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 170 "markdown.lex"
{ 
                                            BEGIN INITIAL; 
                                            yylval.text = strdup("</script>"); 
                                            P("SCRIPTEND"); 
                                            return SCRIPTEND;
                                        }
	YY_BREAK
/* style block */
/* ^\<style[^>]*>/(.|[\r\n])*\<\/style>    { */
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 183 "markdown.lex"
{
                                            yylval.text = strdup(yytext); 
                                            P("STYLESTART"); 
                                            BEGIN STYLEBLOCK; 
                                            return STYLESTART; 
                                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 189 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 190 "markdown.lex"
{ 
                                            yylineno++; 
                                            yylval.text = strdup(yytext); 
                                            P("TEXT"); 
                                            return TEXT; 
                                        }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 196 "markdown.lex"
{ 
                                            yylval.text = "</style>"; 
                                            P("STYLEEND"); 
                                            BEGIN INITIAL; 
                                            return STYLEEND;
                                        }
	YY_BREAK
/* svg block */
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 206 "markdown.lex"
{
                                            yylval.text = strdup(yytext); 
                                            P("SVGSTART"); 
                                            BEGIN SVGBLOCK; 
                                            return SVGSTART; 
                                        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 212 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 213 "markdown.lex"
{ 
                                            yylineno++; 
                                            yylval.text = strdup(yytext); 
                                            P("TEXT"); 
                                            return TEXT; 
                                        }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 219 "markdown.lex"
{ 
                                            yylval.text = "</svg>"; 
                                            P("SVGEND"); 
                                            BEGIN INITIAL; 
                                            return SVGEND;
                                        }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 230 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 231 "markdown.lex"
{ yylineno++; P("LINEBREAK"); return LINEBREAK; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 234 "markdown.lex"
ECHO;
	YY_BREAK
#line 1608 "markdown.lex.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(ESCAPE):
			case YY_STATE_EOF(CODEBLOCK):
			case YY_STATE_EOF(CODESPAN):
			case YY_STATE_EOF(XCODESPAN):
			case YY_STATE_EOF(INDENTLIST):
			case YY_STATE_EOF(SHTMLBLOCK):
			case YY_STATE_EOF(SCRIPTBLOCK):
			case YY_STATE_EOF(STYLEBLOCK):
			case YY_STATE_EOF(SVGBLOCK):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 519 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 519 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 518);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 234 "markdown.lex"



int yywrap(){
    return 1;
}


    /*
    int main(int argc, char **argv){
        yyin = fopen(argv[1], "r");
        yylex();
        fclose(yyin);
    }
    */




